name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # Setting up project
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build project
    - name: Build with Gradle
      run: ./gradlew build

    # Test project
    - name: Test with Gradle
      run: ./gradlew test
    
    # Artifact for later usage
    - name: APK Artifact 
      uses: actions/upload-artifact@v4
      with:
         name: "Build"
         path: app/build/outputs/apk/*
